### PR TITLE
Fixed the issues in the quadrilateral function

### PR DESCRIPTION
**Pull request by diliphridya**
Corrected the bugs in the function and also modified it to remove the dependency on the arrangement of sides.

### CODE REVIEW

**Comment by fverdugo** [comment]
Hi @diliphridya! 

For some reason, the tests were not launched for this PR. Can you pull master and push again?

**Comment by diliphridya** [comment]
Sure.

**Comment by diliphridya** [comment]
@fverdugo 
Please check if its okay now.

**Review by fverdugo — CHANGES_REQUESTED** [review]
@diliphridya can you add a test to make sure that we don't reactivate the bug?

**Comment by diliphridya** [comment]
@fverdugo 
Just clarifying, do I need to add tests for the quadrilateral function?

**Comment by fverdugo** [comment]
yes, add some tests to make sure that now the function works correctly

**Comment by diliphridya** [comment]
Sure.

**Comment by diliphridya** [comment]
@fverdugo 
I  have added a couple of tests. It seems to be working fine now.

**Comment by fverdugo** [comment]
As far I can see, the test you have added only execute code. They do not check if the numerical values are correct.

You can integrate the area of a square `sum(\int(1)d\Omega)` where `d\Omega` corresponds to the embedded mesh for the quadrilateral and check that the value is the correct one with `@test`.

**Comment by diliphridya** [comment]
Okay. I will do that too. Thanks!

**Comment by diliphridya** [comment]
@fverdugo 
I have added the suggested tests too. Please have a look.

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
