### PR TITLE
Compathelper/new version/2020 08 28 00 41 27 065 3907641305

### PR DESCRIPTION
**Pull request by ericneiva**
Dear @fverdugo,

In relation to #24, this PR applies all the changes necessary to support Gridap v0.14, as well as solving the commutativity violation issue.

Please, review and accept the merge request whenever you have time. Thanks. Regards.

### CODE REVIEW

**Comment by ericneiva** [comment]
Tests for julia 1.5 are failing because `GridapEmbeddedTests` take too long to run and do not produce any output for 10 minutes.

I am now reducing the execution time of the `GridapEmbeddedTests`. 

@fverdugo, both `BimaterialPoissonCutFEMTests.jl`and `EmbeddedBimaterialPoissonCutFEMTests.jl` solve a Poisson problem with CutFEM. What do you think of moving one of them to the `examples` folder?

**Comment by fverdugo** [comment]
In Gridap main repo, we have the same problem. I have finally decided to move all the tests in `GridapTests` into a separate job:

https://github.com/gridap/Gridap.jl/blob/8ce2563fe5029d222c69c97cb18a15712169e771/.travis.yml#L18

We can do the same in GridapEmbedded

**Comment by fverdugo** [comment]
You can see all the jobs in action here:
https://travis-ci.com/github/gridap/Gridap.jl/builds/182193982

**Comment by ericneiva** [comment]
I see, I'll do the same in `GridapEmbedded`, thanks.

**Comment by ericneiva** [comment]
> In Gridap main repo, we have the same problem. I have finally decided to move all the tests in GridapTests into a separate job:

I took a look at it and I am not sure this will fix the issue. 

The jobs will still *not produce output for 10 minutes* and Travis will stop. Am I right? 

I think the solution could be something like you did [here](https://github.com/gridap/Gridap.jl/commit/805041106c28fc269aa25757f1d64bca2fd0271c) of splitting the `FE space` tests. What do you think?

**Comment by fverdugo** [comment]
The problem is that the `"GridapEmbedded"` testset takes to long, right? 

https://github.com/gridap/GridapEmbedded.jl/blob/ed31b2b3c29232d2d753c4efaf3cab287f13e942/test/runtests.jl#L17

This are the timing for 1.3:

```
Test Summary: | Pass  Total
CSG           |   44     44
138.804544 seconds (40.47 M allocations: 2.351 GiB, 0.48% gc time)
Test Summary: | Pass  Total
Interfaces    |   45     45
182.038483 seconds (334.32 M allocations: 17.251 GiB, 4.36% gc time)
Test Summary:   | Pass  Total
LevelSetCutters |   22     22
 61.597232 seconds (154.85 M allocations: 15.980 GiB, 6.56% gc time)
Test Summary: |
AgFEM         | No tests
  6.723593 seconds (11.01 M allocations: 589.409 MiB, 1.07% gc time)
Test Summary:  | Pass  Total
GridapEmbedded |   12     12
565.575209 seconds (767.35 M allocations: 38.548 GiB, 2.24% gc time)
Test Summary:    |
PoissonCSGCutFEM | No tests
 46.064784 seconds (66.42 M allocations: 6.946 GiB, 4.53% gc time)
Test Summary:                |
StokesTubeWithObstacleCutFEM | No tests
203.350266 seconds (276.30 M allocations: 13.798 GiB, 2.73% gc time)
```

So the problem is definitively the `"GridapEmbedded"` testset.

If you run directly 

https://github.com/gridap/GridapEmbedded.jl/blob/master/test/GridapEmbeddedTests/runtests.jl

in a separate job, I think it will work since you will execute smaller testsets `""PoissonCutFEM""`, `"PoissonAgFEM"` etc.

Of course, you have to run this file without wrapping it into a testset.

Just copy what is done in Gridap.

On the other hand we have the examples:
https://github.com/gridap/GridapEmbedded.jl/blob/ed31b2b3c29232d2d753c4efaf3cab287f13e942/test/runtests.jl#L19
It seems that they produce enough output.

**Pull request merged**
