### PR TITLE
Moment fitted machinery

### PR DESCRIPTION
**Pull request by pmartorell**
Dear @fverdugo ,

this PR is adding the moment fitted machinery developed by @ericneiva and used in the publication:
https://doi.org/10.1016/j.camwa.2022.09.027 by @santiagobadia , @ericneiva and @fverdugo .

Comments:
* Coverage in [`src/AgFEM/AggregateBoundingBoxes.jl`](https://app.codecov.io/gh/pmartorell/GridapEmbedded.jl/blob/moment_fitted/src/AgFEM/AggregateBoundingBoxes.jl) and  [`src/MomentFitting/JacobiPolynomialBases.jl`](https://app.codecov.io/gh/pmartorell/GridapEmbedded.jl/blob/moment_fitted/src/MomentFitting/JacobiPolynomialBases.jl)
still need to be improved
* The instances of the input variable `cut` in [`src/MomentFitting/CutCellMoments.jl`](https://github.com/pmartorell/GridapEmbedded.jl/blob/a10dc055e9a27faa510291ef75f360f81e15b6e6/src/MomentFitting/CutCellMoments.jl#L21) have no type definition due extensibility issues. `EmbeddedDiscretization`  has no abstract types but `GridapType<:Any`.

### CODE REVIEW

**Comment by ericneiva** [comment]
Hi, @pmartorell , thanks for doing this work :)

> Coverage in [src/AgFEM/AggregateBoundingBoxes.jl](https://app.codecov.io/gh/pmartorell/GridapEmbedded.jl/blob/moment_fitted/src/AgFEM/AggregateBoundingBoxes.jl)

The BBoxes machinery is definitely covered in the [Poisson Modal C0 test](https://github.com/gridap/GridapEmbedded.jl/blob/master/test/GridapEmbeddedTests/PoissonModalC0AgFEMTests.jl#L31), but the tests in the GridapEmbeddedTests folder are not included in the main [runtests.jl](https://github.com/gridap/GridapEmbedded.jl/blob/master/test/runtests.jl). They are tested separately [here](https://github.com/gridap/GridapEmbedded.jl/blob/57626e21b7d94d45d20dd03dc90360a8c8ef6a37/.github/workflows/ci.yml#L72).

Could this be the reason why it appears as "not covered"?

**Comment by pmartorell** [comment]
> They are tested separately [here](https://github.com/gridap/GridapEmbedded.jl/blob/57626e21b7d94d45d20dd03dc90360a8c8ef6a37/.github/workflows/ci.yml#L72).

Indeed. May be convenient to include some tests into the main `runtest.jl` ? To keep the high coverage statistics.

**Comment by fverdugo** [comment]
Hi @ericneiva can you please review the PR?

Once you are happy, I'll merge it.

**Comment by ericneiva** [comment]
Hi, @fverdugo, I am happy to review it, though it's basically my own code extracted from the InterpolatedAgFEM.jl package and cleaned by @pmartorell.

**Comment by pmartorell** [comment]
Hi @ericneiva,
I have found an important bottleneck in memory consumption related with the usage of `CompressedArray` in both modal C0 basis and moment fitting measures. It seems that Gridap is not efficient with `CompressedArray` with a large amount of values, e.g., `CompressedArray(vals,1:length(vals))`. The usage of flat arrays instead will reduce the memory consumption up to one order of magnitude.

A possible optimization would accommodate the Gridap constructors of `CellQuadrature` and `FESpaces` to flat arrays of quadrature and reference FEs, respectively. It is probably better to include this optimization in another PR.

**Comment by ericneiva** [comment]
Hi, @pmartorell, thanks a lot for identifying this.

Is it possible to get rid of the `CompressedArray` usage in the Moment Fitted measures without touching Gridap? If so, could you please update this PR with this optimization?

I agree to change the Gridap constructors in another PR.

**Comment by pmartorell** [comment]
Hi @ericneiva,
the optimization have to be done in Gridap first. Then, eliminating `CompressedArray` in `GridapEmbedded/MomentFittedQuadratures` is straighforward.

I do not have much time for the developments right now. I have tested this by editing the `FESpace` and `CellMeasure` *a posteriori*.

**Comment by ericneiva** [comment]
> the optimization have to be done in Gridap first. 

Okay, thanks for letting me know.

> I do not have much time for the developments right now.

Of course you don't, I know. I was just hoping that changing MomentFittedQuadratures could be quickly done without touching Gridap...

**Comment by ericneiva** [comment]
Hi, @pmartorell, other than the performance issues, which we won't solve now, is there anything left to add to this branch, before merging it with GE?

**Comment by pmartorell** [comment]
Hi @ericneiva , I do not have new changes right now. You can merge it. Thanks for asking.

**Review by ericneiva — APPROVED** [review]
Hi, @fverdugo, this is ready to be merged. 

If you want, I can merge it myself and release GE 0.8.2 (I think I have the permissions).

Let me know if you are ok with this.

@pmartorell Thanks a lot for your work!

**Comment by fverdugo** [comment]
@ericneiva feel free to release a new version.

**Pull request merged**
